In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import preprocessing

In [4]:
import matplotlib.pyplot as plt

In [5]:
import seaborn as sns

In [9]:
df = pd.read_csv(r"C:\Users\HP\Desktop\TE_codes\boston_housing.csv")

In [10]:
df

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     ptratio   black  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [11]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   ptratio   black  lstat  medv  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [12]:
df.tail()

crim   zn  indus  chas    nox     rm   age     dis  rad    tax  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     ptratio   black  lstat  medv  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9

In [13]:
X = df[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'black', 'lstat']]
Y = df[['medv']]

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 0) 

In [15]:
X_train

crim    zn  indus  chas    nox     rm    age     dis  rad    tax  \
141  1.62864   0.0  21.89     0  0.624  5.019  100.0  1.4394    4  437.0   
272  0.11460  20.0   6.96     0  0.464  6.538   58.7  3.9175    3  223.0   
135  0.55778   0.0  21.89     0  0.624  6.335   98.2  2.1107    4  437.0   
298  0.06466  70.0   2.24     0  0.400  6.345   20.1  7.8278    5  358.0   
122  0.09299   0.0  25.65     0  0.581  5.961   92.9  2.0869    2  188.0   
..       ...   ...    ...   ...    ...    ...    ...     ...  ...    ...   
323  0.28392   0.0   7.38     0  0.493  5.708   74.3  4.7211    5  287.0   
192  0.08664  45.0   3.44     0  0.437  7.178   26.3  6.4798    5  398.0   
117  0.15098   0.0  10.01     0  0.547  6.021   82.6  2.7474    6  432.0   
47   0.22927   0.0   6.91     0  0.448  6.030   85.5  5.6894    3  233.0   
172  0.13914   0.0   4.05     0  0.510  5.572   88.5  2.5961    5  296.0   

     ptratio   black  lstat  
141     21.2  396.90  34.41  
272     18.6  394.96   7.73  
135     21.2  394.67  16.96  
298     14.8  368.24   4.97  
122     19.1  378.09  17.93  
..       ...     ...    ...  
323     19.6  391.13  11.74  
192     15.2  390.49   2.87  
117     17.8  394.51  10.30  
47      17.9  392.74  18.80  
172     16.6  396.90  14.69  

[354 rows x 13 columns]

In [16]:
X_test

crim   zn  indus  chas    nox     rm    age     dis  rad    tax  \
329   0.06724  0.0   3.24     0  0.460  6.333   17.2  5.2146    4  430.0   
371   9.23230  0.0  18.10     0  0.631  6.216  100.0  1.1691   24  666.0   
219   0.11425  0.0  13.89     1  0.550  6.373   92.4  3.3633    5  276.0   
403  24.80170  0.0  18.10     0  0.693  5.349   96.0  1.7028   24  666.0   
78    0.05646  0.0  12.83     0  0.437  6.232   53.7  5.0141    5  398.0   
..        ...  ...    ...   ...    ...    ...    ...     ...  ...    ...   
4     0.06905  0.0   2.18     0  0.458  7.147   54.2  6.0622    3  222.0   
428   7.36711  0.0  18.10     0  0.679  6.193   78.1  1.9356   24  666.0   
385  16.81180  0.0  18.10     0  0.700  5.277   98.1  1.4261   24  666.0   
308   0.49298  0.0   9.90     0  0.544  6.635   82.5  3.3175    4  304.0   
5     0.02985  0.0   2.18     0  0.458  6.430   58.7  6.0622    3  222.0   

     ptratio   black  lstat  
329     16.9  375.21   7.34  
371     20.2  366.15   9.53  
219     16.4  393.74  10.50  
403     20.2  396.90  19.77  
78      18.7  386.40  12.34  
..       ...     ...    ...  
4       18.7  396.90   5.33  
428     20.2   96.73  21.52  
385     20.2  396.90  30.81  
308     18.4  396.90   4.54  
5       18.7  394.12   5.21  

[152 rows x 13 columns]

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [18]:
X_train

array([[-0.20735619, -0.49997924,  1.54801583, ...,  1.2272573 ,
         0.42454294,  3.10807269],
       [-0.38886492,  0.34677427, -0.58974728, ...,  0.05696346,
         0.40185312, -0.66643035],
       [-0.33573486, -0.49997924,  1.54801583, ...,  1.2272573 ,
         0.39846135,  0.63936662],
       ...,
       [-0.38450355, -0.49997924, -0.15303077, ..., -0.30312696,
         0.39659002, -0.30284441],
       [-0.37511786, -0.49997924, -0.59690657, ..., -0.25811566,
         0.37588849,  0.89967717],
       [-0.38592298, -0.49997924, -1.00641779, ..., -0.84326258,
         0.42454294,  0.31822262]])

In [22]:
X_test

array([[-0.45379523, -0.45888196, -1.2285158 , ..., -0.74998219,
         0.26955997, -0.79993845],
       [ 0.55063352, -0.45888196,  1.04438686, ...,  0.88492032,
         0.18133643, -0.49829647],
       [-0.44864325, -0.45888196,  0.40044876, ..., -0.99769469,
         0.4499995 , -0.36469248],
       ...,
       [ 1.38129558, -0.45888196,  1.04438686, ...,  0.88492032,
         0.48077063,  2.43272702],
       [-0.407137  , -0.45888196, -0.20983937, ..., -0.00684469,
         0.48077063, -1.18559943],
       [-0.45789292, -0.45888196, -1.39064748, ...,  0.14178281,
         0.45369983, -1.09331627]])

In [23]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, Y_train)
Y_pred = lr.predict(X_test)

In [25]:
print(Y_pred)

[[26.00247623]
 [24.12967879]
 [30.19850019]
 [12.66547763]
 [22.31194771]
 [19.85804475]
 [21.05999015]
 [22.02518198]
 [19.936078  ]
 [21.23164487]
 [ 7.09120928]
 [17.91928076]
 [17.75563409]
 [ 6.16905647]
 [40.99559869]
 [33.96879837]
 [22.95943305]
 [38.35013311]
 [31.9897383 ]
 [23.9729526 ]
 [25.53935454]
 [25.71895133]
 [21.16764503]
 [31.51433926]
 [23.40163063]
 [10.95647839]
 [18.14704735]
 [19.5977375 ]
 [36.4686675 ]
 [21.68883962]
 [18.83731101]
 [18.24655181]
 [20.55638686]
 [24.99042008]
 [29.93798097]
 [19.72193033]
 [11.90555681]
 [24.98329955]
 [18.91726884]
 [16.28696151]
 [27.46413688]
 [21.93899465]
 [23.32840399]
 [16.07579184]
 [23.90790601]
 [25.9539343 ]
 [21.17024648]
 [24.0944561 ]
 [11.18435673]
 [24.85967622]
 [22.81090229]
 [18.39602386]
 [25.39884892]
 [31.12742347]
 [14.26336398]
 [22.99005947]
 [21.91826629]
 [16.27316463]
 [15.57560976]
 [22.88929286]
 [18.58742699]
 [22.48859775]
 [34.20867069]
 [32.24285896]
 [18.36455665]
 [34.0040176 ]
 [19.31749

In [26]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
print("Root Mean Squared Error is: ")
rmse

Root Mean Squared Error is: 


5.327467544626455

In [27]:
print("Training accuracy is: ")
lr.score(X_train, Y_train)

Training accuracy is: 


0.7645451026942549

In [28]:
print("Testing accuracy is: ")
lr.score(X_test, Y_test)

Testing accuracy is: 


0.6591396211105127